const express = require('express');
const PDFDocument = require('pdfkit');
const db = require('../db');
const { requireAuth } = require('../middleware/auth');
const { computeBadges, getHistory, getWorkerRatings, avgRating } = require('../util');

const router = express.Router();

function buildPassport(u) {
  const history = getHistory(u.id);
  const ratings = getWorkerRatings(u.id);
  const avg = avgRating(ratings);
  return {
    id: u.id, name: u.name, trade: u.trade, score: u.score,
    badges: computeBadges(u, history, avg, ratings.length),
    avgRating: avg, ratingsCount: ratings.length,
    history: history.map(h => ({ type: h.type, trade: h.trade, label: h.label, points: h.points, ts: h.ts })),
    memberSince: u.created_at,
  };
}

// GET /api/passport/me
router.get('/me', requireAuth, (req, res) => {
  if (req.user.role !== 'youth') return res.status(403).json({ error: 'Only worker accounts have a passport' });
  res.json({ passport: buildPassport(req.user) });
});

// GET /api/passport/verify/:id — public verification (no auth), used by the "Verify a Skill Passport" screen
router.get('/verify/:id', (req, res) => {
  const u = db.prepare("SELECT * FROM users WHERE id = ? AND role = 'youth' AND active = 1").get(req.params.id);
  if (!u) return res.status(404).json({ error: 'No passport found with that ID' });
  const p = buildPassport(u);
  res.json({ passport: { id: p.id, name: p.name, trade: p.trade, score: p.score, badges: p.badges, avgRating: p.avgRating, ratingsCount: p.ratingsCount, memberSince: p.memberSince } });
});

// GET /api/passport/me/pdf — download a printable Skill Passport
router.get('/me/pdf', requireAuth, (req, res) => {
  if (req.user.role !== 'youth') return res.status(403).json({ error: 'Only worker accounts have a passport' });
  const p = buildPassport(req.user);

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="SkillSetu-Passport-${p.id}.pdf"`);

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  doc.pipe(res);

  doc.fontSize(22).fillColor('#0f5132').text('SkillSetu — Skill Passport', { align: 'left' });
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#666').text(`Passport ID: ${p.id}`);
  doc.moveDown(1);

  doc.fontSize(16).fillColor('#111').text(p.name);
  doc.fontSize(12).fillColor('#333').text(`Primary trade: ${p.trade || '—'}`);
  doc.text(`Skill score: ${p.score}/100`);
  doc.text(`Trust rating: ${p.ratingsCount ? p.avgRating.toFixed(1) + ' / 5 (' + p.ratingsCount + ' ratings)' : 'No ratings yet'}`);
  doc.moveDown(1);

  doc.fontSize(14).fillColor('#0f5132').text('Badges earned');
  doc.fontSize(11).fillColor('#333');
  if (!p.badges.length) doc.text('None yet.');
  else p.badges.forEach(b => doc.text(`• ${b.replace(/_/g, ' ')}`));
  doc.moveDown(1);

  doc.fontSize(14).fillColor('#0f5132').text('Verified history');
  doc.fontSize(11).fillColor('#333');
  if (!p.history.length) doc.text('No history yet.');
  else p.history.slice(0, 25).forEach(h => {
    doc.text(`• [${new Date(h.ts).toLocaleDateString()}] ${h.label}`);
  });

  doc.moveDown(1.5);
  doc.fontSize(9).fillColor('#888').text('Generated by SkillSetu. Verify this passport at /verify using the Passport ID above.');
  doc.end();
});

module.exports = router;
